# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0003_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.TextField(default='action'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='score',
            field=models.IntegerField(default=''),
        ),
    ]
