# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0004_auto_20170126_1026'),
        ('gamesite', '0003_userprofile'),
    ]

    operations = [
    ]
