# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0004_auto_20170305_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='skey',
        ),
    ]
