# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamesite', '0005_merge_20170219_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225)),
                ('game_url', models.URLField(default='')),
                ('price', models.IntegerField(default=15)),
                ('image_url', models.URLField(default='')),
                ('websiteURL', models.CharField(blank=True, max_length=225)),
                ('sid', models.CharField(blank=True, max_length=225)),
                ('skey', models.CharField(blank=True, max_length=225)),
                ('genre', models.TextField(default='action')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websiteURL', models.CharField(blank=True, max_length=225)),
                ('score', models.IntegerField(default='')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
