# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0007_auto_20170223_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.SmallIntegerField(default=15, max_length=250),
        ),
        migrations.AddField(
            model_name='game',
            name='websiteId',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gamesite.UserProfile'),
        ),
    ]
