# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0008_auto_20170224_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_file',
            new_name='game_url',
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.SmallIntegerField(default=15),
        ),
    ]
