# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0009_auto_20170224_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='skey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
