# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0011_auto_20170224_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='skey',
        ),
        migrations.RemoveField(
            model_name='game',
            name='websiteId',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_url',
            field=models.URLField(default=b'http://webcourse.cs.hut.fi/example_game.html'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
