# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0012_auto_20170224_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_url',
            field=models.URLField(default=b''),
        ),
    ]
