# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0013_auto_20170224_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.TextField(default=b'action'),
        ),
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(default=b''),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='game',
            name='sid',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='game',
            name='skey',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='game',
            name='websiteURL',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
