# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0014_auto_20170224_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websiteURL', models.CharField(blank=True, max_length=225)),
                ('score', models.IntegerField(default=b'')),
            ],
        ),
    ]
