# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0017_auto_20170225_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=225)),
                ('sid', models.CharField(blank=True, max_length=225)),
                ('ref', models.IntegerField(default=None)),
                ('checksum', models.CharField(blank=True, max_length=225)),
                ('result', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
