# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0018_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AlterField(
            model_name='payment',
            name='result',
            field=models.CharField(default='failed', max_length=20),
        ),
    ]
