# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0019_auto_20170302_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='result',
            field=models.CharField(max_length=20),
        ),
    ]
