# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0020_auto_20170302_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default='2017-03-02 10:20:35'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.IntegerField(blank=True),
        ),
    ]
