# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesite', '0021_auto_20170302_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.IntegerField(null=True),
        ),
    ]
